### ISSUE TITLE
Fatal error when trying to install on Kubuntu 20.03.03

### ISSUE THREAD

**Issue by pypeaday** [MonolithProjects/ansible-homebrew#10]
When trying to use this role to install homebrew on my Kubuntu machine I get a fatal error pointing to `./tasks/formulae.yml`

```
fatal: [localhost]: FAILED! => {"reason": "couldn't resolve module/action 'community.general.homebrew'. This often indicates a misspelling, missing collection, or incorrect module path.\n\nThe error appears to be in '/home/nic/.ansible/roles/monolithprojects.homebrew/tasks/formulae.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Install Formula\n  ^ here\n"}
```

I'm not an ansible wizard so I'm not sure if I should just fork this repo and play with those line endings or if there's a shell setting difference?  

ansible version is 2.9.6 installed with `apt`

**Comment by MonolithProjects** [comment]
Hi @nicpayne713 it should work with Ansible 2.10+. The task name is in FQCN format which comes with Ansible 2.10 (Looks like i falsely noted in the galaxy metadata that this role works with Ansible 2.9+)
